version: 2.1
orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    working_directory: ~/us-district-map
    docker:
      - image: cimg/node:15.5.0
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: Run Tests
          command: npm test
      - store_test_results:
          path: ~/test-results

workflows:
  run_test:
    jobs:
      - build
