version: 2.1

jobs:
  build:
    working_directory: ~/us-district-map
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@5"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Make test result directory
          command: mkdir test-results
      - run:
          name: Run Tests
          command: npm test
      - store_test_results:
          path: test-results

workflows:
  run_test:
    jobs:
      - build
